### ISSUE TITLE
Rename route profile_config_gmf2 to more standard name

### ISSUE THREAD

**Issue by monodo** [sitn/pytree#10]
@kalbermattenm could you please rename the profile_config_gmf2 to something more standard as mentionned here: https://github.com/camptocamp/ngeo/pull/3464 ?

**Comment by kalbermattenm** [comment]
What about `/profile/conf` ?

**Comment by kalbermattenm** [comment]
or `/profile/config` ?

**Comment by kalbermattenm** [comment]
Moreover, we should change the whole API...

Routes would be:

* `/profile/get` (for `/get_profile`)
* `/profile_v1/get` -> Is that used ?? (for `/get_profile_gmf1/profile`)
* `/dem/get` (for `/get_gmf_dem_dsm`)
* `/profile/config` (for `/profile_config_gmf2`)

??

**Comment by monodo** [comment]
Tiptop :-)

**Comment by monodo** [comment]
@gnerred remember to update the route names client side next time you update your pytree instance

**Comment by gnerred** [comment]
Thanks @monodo
